language: r

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    name: tidyr-devel
    before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
  - r: oldrel
  
sudo: false
cache: packages

r_packages: 
  - covr

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
