app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(SCD_es_calculator = "Multiple-Series Calculator")
app$setInputs(dat_type = "dat")
app$uploadFile(dat = "ex_issue73.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(BatchEntryTabs = "Variables")
app$setInputs(calcPhasePair = TRUE)
app$setInputs(b_clusters = "Behavior_type")
app$setInputs(b_clusters = c("Behavior_type", "Case_pseudonym"))
app$setInputs(b_aggregate = "phase_pair_calculated")
app$setInputs(b_phase = "Condition")
app$setInputs(session_number = "Session_number")
app$setInputs(b_out = "Outcome")
app$setInputs(bimprovement = "series")
app$setInputs(bseldir = "Direction")
app$setInputs(BatchEntryTabs = "Plot")
app$setInputs(BatchEntryTabs = "Estimate")
app$setInputs(bESpar = "LRRi")
app$setInputs(bESpar = c("LRRd", "LRRi"))
app$setInputs(boutScale = "series")
app$setInputs(bscalevar = "Metric")
app$setInputs(batchest = "click")
app$snapshot()
